### ISSUE TITLE
Add YOLOS

### ISSUE THREAD

**Issue by NielsRogge** [IDEACVR/awesome-detection-transformer#1]
Hi,

Thanks for this great repo. A paper I particularly liked is YOLOS: https://github.com/hustvl/YOLOS.

It basically shows that you can replace the convolutional backbone + encoder-decoder Transformer by just a single Transformer encoder.

Maybe you can add it as well? :)

**Comment by IDEACVR** [comment]
Thanks for your valuable suggestions. We have added YOLOS in the latest update.
